suggested edit for readme
followed these instructions and  got the following error...
```
webpack.config.js:11
} = require('@magento/pwa-buildpack');
    ^

TypeError: Cannot match against 'undefined' or 'null'.
```

When I changed 
```
const {
       Webpack: {
```
To...
```
const {
       WebpackTools: {
```